#!/bin/bash

set -xe

cat ./current-app-info/current-app.txt
pwd
ls ./current-app-info/
sed "s/APPNAME/$(cat ./current-app-info/next-app.txt)-$PWS_APP_SUFFIX/" ./smart-contracts-ui/manifest.yml > ./app-manifest-output/manifest.yml

cat ./app-manifest-output/manifest.yml
