---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: djudorange/node-gulp-mocha
    tag: "latest"

inputs:
- name: smart-contracts-ui

run:
  path: smart-contracts-ui/ci/tasks/run-unit-tests
