---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"


inputs:
- name: smart-contracts-ui
- name: current-app-info

run:
  path: smart-contracts-ui/ci/tasks/update-routes
