groups:
- name: cf-pas-apps
  jobs:
  - unit-tests
  - deploy-app
  - load-tests
  - promote-new-version

resources:
- name: smart-contracts-ui
  type: git
  source:
    branch: master
    uri: https://github.com/pivotal-mea-pa/smart-contracts-ui.git

- name: pivotal-cloud-foundry
  type: cf
  source:
    api: {{pws-api}}
    organization: {{pws-organization}}
    username: {{deploy-username}}
    password: {{deploy-password}}
    skip_cert_check: true
    space: {{pws-space}}

jobs:
- name: unit-tests
  serial: true
  public: true
  plan:
  - get: smart-contracts-ui
    trigger: true
  - task: run-unit-tests
    file: smart-contracts-ui/ci/tasks/unit-tests.yml

- name: deploy-app
  serial: true
  public: true
  plan:
  - get: smart-contracts-ui
    trigger: true
    passed:
      - unit-tests
  - task: get-current-app-color
    file: smart-contracts-ui/ci/tasks/current-app-get-info.yml
    params:
      PWS_APP_SUFFIX: {{pws-app-suffix}}
      PWS_API: {{pws-api}}
      PWS_ORG: {{pws-organization}}
      PWS_USER: {{deploy-username}}
      PWS_PWD: {{deploy-password}}
      PWS_SPACE: {{pws-space}}
  - task: prepare-app-manifest
    file: smart-contracts-ui/ci/tasks/app-manifest-prep.yml
    params:
      PWS_APP_SUFFIX: {{pws-app-suffix}}
  - put: pivotal-cloud-foundry
    params:
      manifest: app-manifest-output/manifest.yml
      path: smart-contracts-ui

- name: load-tests
  serial: true
  public: true
  plan:
  - get: smart-contracts-ui
    trigger: true
    passed:
      - deploy-app
  - task: get-current-app-color
    file: smart-contracts-ui/ci/tasks/current-app-get-info.yml
    params:
      PWS_APP_SUFFIX: {{pws-app-suffix}}
      PWS_API: {{pws-api}}
      PWS_ORG: {{pws-organization}}
      PWS_USER: {{deploy-username}}
      PWS_PWD: {{deploy-password}}
      PWS_SPACE: {{pws-space}}
  - task: run-load-tests
    file: smart-contracts-ui/ci/tasks/load-tests.yml
    params:
      PWS_APP_SUFFIX: {{pws-app-suffix}}
      PWS_APP_DOMAIN: {{pws-app-domain}}

- name: promote-new-version
  serial: true
  public: true
  plan:
  - get: smart-contracts-ui
    trigger: true
    passed:
      - load-tests
  - task: get-current-app-color
    file: smart-contracts-ui/ci/tasks/current-app-get-info.yml
    params:
      PWS_APP_SUFFIX: {{pws-app-suffix}}
      PWS_API: {{pws-api}}
      PWS_ORG: {{pws-organization}}
      PWS_USER: {{deploy-username}}
      PWS_PWD: {{deploy-password}}
      PWS_SPACE: {{pws-space}}
  - task: switch-app-routes
    file: smart-contracts-ui/ci/tasks/update-routes.yml
    params:
      PWS_APP_SUFFIX: {{pws-app-suffix}}
      PWS_APP_DOMAIN: {{pws-app-domain}}
      PWS_API: {{pws-api}}
      PWS_ORG: {{pws-organization}}
      PWS_USER: {{deploy-username}}
      PWS_PWD: {{deploy-password}}
      PWS_SPACE: {{pws-space}}